### Test MiniAM2 building and predict

In [1]:
import tensorflow as tf
import keras
from keras import layers, Model
import logging

logging.basicConfig(level=logging.INFO)

In [2]:
from src.classifiers.miniam2 import MiniAM2Classifier

miniam2 = MiniAM2Classifier()
miniam2.model.summary()


INFO:root:Do not standardize
INFO:root:Do not standardize
INFO:root:Do not standardize


Model: "MiniAM2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 screen_name (InputLayer)       [(None, 1)]          0           []                               
                                                                                                  
 name (InputLayer)              [(None, 1)]          0           []                               
                                                                                                  
 bio (InputLayer)               [(None, 1)]          0           []                               
                                                                                                  
 tf.identity (TFOpLambda)       (None, 1)            0           ['screen_name[0][0]']            
                                                                                            

### Adapt tokenizers to a data

In [3]:
from src.utils import get_data

# We will read only a few lines (50) of the dataset in orther to pass this test faster
data = get_data('data/training_data/soft_labeled_data.zip', nrows=500)
miniam2.adapt_text_models_tokenizers(data)

INFO:root:Adapting vocabularies...
2023-05-23 17:48:20.792075: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
INFO:root:Adapted.
INFO:root:Adapting vocabularies...
INFO:root:Adapted.
INFO:root:Adapting vocabularies...
INFO:root:Adapted.
INFO:root:Adapting vocabularies...
INFO:root:Adapted.
INFO:root:Adapting vocabularies...
INFO:root:Adapted.


### Predict using MiniAM2 model (randomly initialized)

In [4]:
miniam2.predict(data.iloc[0:3])

1/1 [==============================] - 0s 137ms/step


array([[0.3311035 , 0.32835606, 0.34054047],
       [0.3320641 , 0.32862508, 0.33931082],
       [0.34194294, 0.33009568, 0.32796136]], dtype=float32)

### Predict using a text model inside MiniAM2, for example, the text model reading the screen_name (randomly initialized)

In [5]:
miniam2.text_models['screen_name_ffnn_char'].predict(data.iloc[0:3])

1/1 [==============================] - 0s 44ms/step


array([[0.34032694, 0.33676648, 0.3229066 ],
       [0.3431533 , 0.32285357, 0.33399314],
       [0.33692533, 0.34524602, 0.3178287 ]], dtype=float32)

### Load existing MiniAM2 saved version

In [6]:
miniam2.load_model_from_path('models', version='0.0.1')

INFO:root:Trained model found with specified filename: models/MiniAM2/version/0.0.1


In [11]:
miniam2.predict(data.iloc[10:20])

1/1 [==============================] - 0s 29ms/step


array([[1.29727717e-03, 9.94214594e-01, 4.48815525e-03],
       [3.39894541e-05, 4.99943420e-02, 9.49971676e-01],
       [1.33793405e-03, 7.09884346e-01, 2.88777709e-01],
       [1.11658324e-03, 8.40300322e-01, 1.58583075e-01],
       [4.15685703e-04, 9.98380542e-01, 1.20376854e-03],
       [1.45674255e-02, 8.71377647e-01, 1.14054978e-01],
       [8.31290090e-05, 1.63530976e-01, 8.36385906e-01],
       [4.67333535e-04, 2.03208372e-01, 7.96324313e-01],
       [1.94452784e-03, 1.19756080e-01, 8.78299415e-01],
       [2.58967914e-02, 2.66250253e-01, 7.07853019e-01]], dtype=float32)

In [12]:
data.iloc[10:20]

name      screen_name  \
10                                      Jérémy         JeremB64   
11  Sra Paula María de Kaya 😎💥🤍🤭😂 NO SOY VIUDA     violetaBolat   
12                                  grapejuice     lesbianhalos   
13                                       oliii       olivia_lte   
14                                 Joshua Cale      JoshuaCale4   
15                            Matías Torriglia  matiastorriglia   
16                                      ella 💫     mstrinakayla   
17                             María Alejandra    marialecaloca   
18                        The King Of Africa 🌍   Layne_JazzeySA   
19                                       Frank      frankxd1000   

                                                  bio  \
10  Construction Engineer at TOTALENERGIES / un pa...   
11                                    BahtOyunu❣Yargı   
12                        thanks for the flag, love 🌈   
13                                                      
14  27. Be Kind to Yourself and Stand Up for Yours...   
15                                       Medicina UNC   
16  20 (sí/í) déghnéasach. sóisialach, feimineach,...   
17  El mejor momento es AHORA!, recuerda que eres ...   
18                                                 🇿🇦   
19                                                      

                                                 text  m3 lang  \
10  Mon album préféré qui m'a laissé les meilleurs...   0   fr   
11  Todavia no vi el fragman subtitulado estoy re ...   2   es   
12  work is kinda busy but i like it https://t.co/...   2   en   
13                      Ta vérité n’est pas la mienne  -1   fr   
14  Cleanse your mind of all bad vibes and let the...   1   en   
15                                  Maybe I maybe you   1   en   
16  Dancing in your underwear in your ancestral ho...   2   en   
17  Mimar el cuerpo, calmar la mente y saciar el a...   2   es   
18  Marriages do face hardships. Couples do agree ...  -1   en   
19  @CarlosA26265000 4 aunque te cueste, porque si...   1   es   

                                               bio_pp  \
10  construction engineer at totalenergies un palo...   
11                                     bahtoyunuyargi   
12                           thanks for the flag love   
13                                                      
14      be kind to yourself and stand up for yourself   
15                                       medicina unc   
16  si i deghneasach soisialach feimineach poblach...   
17  el mejor momento es ahora recuerda que eres tu...   
18                                                      
19                                                      

                                              text_pp  \
10  mon album prefere qui m a laisse les meilleurs...   
11  todavia no vi el fragman subtitulado estoy re ...   
12  work is kinda busy but i like it https t co vu...   
13                      ta verite n est pas la mienne   
14  cleanse your mind of all bad vibes and let the...   
15                                  maybe i maybe you   
16  dancing in your underwear in your ancestral ho...   
17   mimar el cuerpo calmar la mente y saciar el alma   
18  marriages do face hardships couples do agree o...   
19  carlosa aunque te cueste porque si no va a val...   

                                 name_pp   screen_name_pp  ...  orgpr_t  \
10                                jeremy           jeremb  ...     -1.0   
11  sra paula maria de kaya no soy viuda     violetabolat  ...     -1.0   
12                            grapejuice     lesbianhalos  ...     -1.0   
13                                 oliii       olivia lte  ...     -1.0   
14                           joshua cale       joshuacale  ...     -1.0   
15                      matias torriglia  matiastorriglia  ...     -1.0   
16                                  ella     mstrinakayla  ...     -1.0   
17                       maria alejandra    marialecaloca  ...     -1.0   
18                